version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2-jdk

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      - run:
          name: SetUp Build
          command: chmod 755 gradlew

      - restore_cache:
          key: dependencies-{{ checksum "build.gradle" }}

      - run:
          name: gradle dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths: ~/.gradle
          key: dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Build apk
          command: ./gradlew clean build

      - run:
          name: Report file move
          command: |
            mv build/reports/checkstyle report/functions/static/checkstyle
            mv build/reports/spotbugs report/functions/static/spotbugs
            mv build/reports/tests report/functions/static/tests

      - persist_to_workspace:
          root: .
          paths:
            - .


  report:
    docker:
      - image: circleci/node:10.16.3

    working_directory: report

    steps:
      - attach_workspace:
          at: .

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "functions/package.json" }}

      - run: ls -ltrA

      - run: cd functions && npm install

      - run:
          name: 'Install Dependencies'
          command: npm install --save-dev firebase-tools

      - save_cache:
          paths:
            - functions/node_modules
          key: v1-dependencies-{{ checksum "functions/package.json" }}

      - run:
          name: 'set .firebaserc id & pass'
          command: |
            echo -e "{\n  {\n    \"projects\": {\n\        "default\": \"$FIREBASE_PJ\"\n  }\n}" > .firebaserc
            sed -i -e 's/"user"/"$BASIC_USER"/' functions/index.js
            sed -i -e 's/"pass"/"$BASIC_PASS"/' functions/index.js
            rm functions/index.js-e

      - run:
          name: 'Deploy to Firebase'
          command: cd report && ../node_modules/.bin/firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"


workflows:
  version: 2
  all_script:
    jobs:
    - build:
        filters:
          branches:
            only: develop
    - report:
        requires:
          - build